### ISSUE TITLE
Dot Dir issue

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/integration-test2#16]
when I run `./run_restricted.sh` I get the following error:

```
Traceback (most recent call last):
  File "experiment.py", line 30, in <module>
    main()
  File "experiment.py", line 25, in main
    backend.run(project_list, args, kernel_dir)
  File "/Users/schaef/git/integration-test2/backend.py", line 119, in run
    generate_project_kernel(project, common.CLUSTER_FILE)
  File "/Users/schaef/git/integration-test2/backend.py", line 51, in generate_project_kernel
    out_dir = dot.dot_dirs(project)[0]
```

@tim-mccarthy @langkymus didn't you fix that in the last PR?

**Comment by martinschaef** [comment]
So, it's looking for dot files in XYZ/dljc-out/dot, but they actually are in dljc-out/_classes

**Comment by martinschaef** [comment]
My bad - didn't run fetch_dependency first ...
