### ISSUE TITLE
Frontend exception

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/integration-test2#18]
When running `run_mini.sh`:

```
[u'Sort10', u'Sort09', u'Sort07']
Traceback (most recent call last):
  File "experiment.py", line 30, in <module>
    main()
  File "experiment.py", line 27, in main
    frontend.run(project_list, args, kernel_dir)
  File "/Users/schaef/git/integration-test2/frontend.py", line 126, in run
    check_similarity(project, result_file, kernel_file, args.cluster, min(5,len(project_list)))
  File "/Users/schaef/git/integration-test2/frontend.py", line 115, in check_similarity
    result_dict[dot_method].append((corpus_dot_to_method_map[dt], score))
KeyError: '/Users/schaef/git/integration-test2/corpus/Sort09/dljc-out/dot/_classes/000000002.dot'
```

**Comment by tim-mccarthy** [comment]
I think I've fixed this, closing for now. Can reopen later if someone can reproduce it.
