### ISSUE TITLE
bixie fails on jmonkey

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/integration-test2#24]
```
Cleaning jmonkeyengine
Running /Users/schaef/git/integration-test2/tools/do-like-javac/dljc -l /Users/schaef/git/integration-test2/libs -o dljc-out -t bixie -- gradle compileJava
Traceback (most recent call last):
  File "/Users/schaef/git/integration-test2/tools/do-like-javac/dljc", line 5, in <module>
    do_like_javac.run()
  File "/Users/schaef/git/integration-test2/tools/do-like-javac/do_like_javac/command.py", line 27, in main
    tools.run(args, javac_commands, jars)
  File "/Users/schaef/git/integration-test2/tools/do-like-javac/do_like_javac/tools/__init__.py", line 42, in run
    TOOLS[tool].run(args, javac_commands, jars)
  File "/Users/schaef/git/integration-test2/tools/do-like-javac/do_like_javac/tools/bixie.py", line 27, in run
    common.run_cmd(cmd)
  File "/Users/schaef/git/integration-test2/tools/do-like-javac/do_like_javac/tools/common.py", line 49, in run_cmd
    print ("Running %s" % ' '.join(cmd))
TypeError: sequence item 6: expected string, NoneType found
```

**Comment by martinschaef** [comment]
@tim-mccarthy maybe you can help me with that ... not urgent though

**Comment by tim-mccarthy** [comment]
Fixed this issue on the DLJC end.
