### ISSUE TITLE
run_restricted.sh fails

### ISSUE THREAD

**Issue by dddejan** [aas-integration/integration-test2#36]
```
Running java -jar /home/dejan/workspace/integration-test2/libs/clusterer.jar -cs 3 -out /home/dejan/workspace/integration-test2/clusters.json -cfm /home/dejan/workspace/integration-test2/c2f.json -wfm ./word_based_field_clusters.json -dirs /home/dejan/workspace/integration-test2/corpus/jreactphysics3d/target/classes /home/dejan/workspace/integration-test2/corpus/react/target/classes
Warning: gnu.trove.map.TObjectIntMap is a phantom class!
Warning: gnu.trove.list.TIntList is a phantom class!
Warning: gnu.trove.list.array.TIntArrayList is a phantom class!
Warning: gnu.trove.iterator.TObjectIntIterator is a phantom class!
Warning: gnu.trove.map.hash.TObjectIntHashMap is a phantom class!
Warning: gnu.trove.stack.TIntStack is a phantom class!
Warning: gnu.trove.map.TIntObjectMap is a phantom class!
Warning: gnu.trove.map.hash.TIntObjectHashMap is a phantom class!
Warning: gnu.trove.set.hash.TIntHashSet is a phantom class!
Warning: gnu.trove.set.TIntSet is a phantom class!
Warning: gnu.trove.iterator.TIntIterator is a phantom class!
Warning: gnu.trove.stack.array.TIntArrayStack is a phantom class!
Total classes loaded: 379
Total clusters: 262
Total clusters >1: 35
Relabeled terms : 107
Print field mapping for 73 classes.
Generate jaif file
Traceback (most recent call last):
  File "experiment.py", line 30, in <module>
    main()
  File "experiment.py", line 25, in main
    backend.run(project_list, args, kernel_dir)
  File "/home/dejan/workspace/integration-test2/backend.py", line 115, in run
    compute_clusters_for_classes(project_list, common.CLUSTER_FILE, common.CLASS2FIELDS_FILE)
  File "/home/dejan/workspace/integration-test2/backend.py", line 96, in compute_clusters_for_classes
    map2annotation.field_mappings_to_annotation(project_list, wf_map_file_name)
  File "/home/dejan/workspace/integration-test2/map2annotation/map2annotation.py", line 24, in field_mappings_to_annotation
    convert_2_ontology_value(ontology_set)
  File "/home/dejan/workspace/integration-test2/map2annotation/map2annotation.py", line 128, in convert_2_ontology_value
    pa2checker.revert_checker_source()
  File "/home/dejan/workspace/integration-test2/pa2checker/pa2checker.py", line 8, in revert_checker_source
    with common.cd(SOLVER_SRC_DIR):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/dejan/workspace/integration-test2/common.py", line 59, in cd
    os.chdir(os.path.expanduser(newdir))
OSError: [Errno 2] No such file or directory: '/home/dejan/workspace/integration-test2/tools/ontology/src/ontology'
```

**Comment by martinschaef** [comment]
Looks like the tar for Daikon is corrupt:
In `fetch_dependencies.sh`:
```
if [ ! -d daikon-src ]; then
    curl -L -o daikon-src.tgz http://plse.cs.washington.edu/daikon/download/daikon-5.4.6.tar.gz
    bash ../build_daikon.sh `pwd`/daikon-src.tgz
    cp daikon-src/daikon.jar ../libs/daikon.jar
fi
```
I get:
```
etching Daikon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1080    0  1080    0     0   5398      0 --:--:-- --:--:-- --:--:--  5427
JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/
~/git/integration-test2/tools ~/git/integration-test2/tools
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
../build_daikon.sh: line 12: pushd: daikon-src: No such file or directory
../build_daikon.sh: line 14: scripts/daikon.bashrc: No such file or directory
make: *** java: No such file or directory.  Stop.
```

**Comment by markro49** [comment]
we make a drop at the first of every month.  the current version is now 5.5.0.

**Comment by martinschaef** [comment]
Cool. Who is in charge of updating this? And why do the old files not work anymore?

**Comment by markro49** [comment]
the old files are moved to the history directory - complete archive of all releases.  

For example: http://plse.cs.washington.edu/daikon/history/daikon-5.4.6/daikon-5.4.6.tar.gz

**Comment by tim-mccarthy** [comment]
OK, so the thing to do for the sake of stability is probably to stay a month behind and point to the last release.

**Comment by markro49** [comment]
and/or I could generate a pull request to the script when we make a drop?

**Comment by tim-mccarthy** [comment]
That works, too.

**Comment by mernst** [comment]
Separately:  can you update `fetch_dependencies.sh` so that the curl command fails if it cannot download the file?  That will give a more informative error message.  The problem wasn't that the .tar.gz file was corrupt, but that it didn't exist at the given URL.

**Comment by markro49** [comment]
per a suggestion from Michael, I have added links to the previous version in the download directory.  I will add this to the release procedure.

**Comment by tim-mccarthy** [comment]
I updated the dependency fetcher with the latest version and added a friendlier error message if a curl fetch fails.
